name: medscribe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ffmpeg
  - numpy=1.24.3
  - pandas=2.1.4
  - pip:
    - streamlit==1.31.0
    - openai-whisper==20231117
    - ffmpeg-python==0.2.0
    - requests==2.31.0
    - python-dotenv==1.0.0